# Generated by Django 3.2.15 on 2022-09-23 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='province',
        ),
    ]
