# Generated by Django 3.2.15 on 2022-09-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0005_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_pic', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=80)),
                ('score', models.IntegerField()),
            ],
        ),
    ]
