# Generated by Django 3.2.15 on 2022-09-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0006_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
