# Generated by Django 4.1 on 2022-09-25 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0007_alter_choice_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='votable_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
