# Generated by Django 4.1 on 2022-09-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0009_alter_user_votable_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='votable_time',
            field=models.DateTimeField(),
        ),
    ]
